apply plugin: "com.gradleup.shadow"

dependencies {
    implementation "com.github.knokko:vk-boiler:$boilerVersion"
    implementation platform("org.junit:junit-bom:5.10.0")
    implementation "org.junit.jupiter:junit-jupiter:5.10.0"
    runtimeOnly("org.junit.platform:junit-platform-launcher")
}

shadowJar {
    manifest {
        attributes ("Main-Class": "com.github.knokko.compressor.TestHelper")
    }
}

tasks.register("assertImageEqual", JavaExec) {
    description = "Checks whether 2 image files are equal: use e.g. ./gradlew assertImageEqual --args=\"expected.png actual.png\""
    classpath = sourceSets.main.runtimeClasspath
    mainClass = "com.github.knokko.compressor.TestHelper"
}
