name: Testing BC7 encoding on MacOS and in a Docker container

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test -p bc7 --tests "com.github.knokko.compressor.TestBc7Compression.testCompressDreamShrine"
      - name: Store test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-macos
          path: build/reports
  test-docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - uses: actions/checkout@v4
      - run: apt update
      - run: apt install openjdk-17-jdk libomp-dev -y
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test -p bc7 --tests "com.github.knokko.compressor.TestBc7Compression.testCompressDreamShrine"
      - name: Store test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-docker
          path: build/reports
