name: Testing with Java 17 and Java 21 on Linux and Windows

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test_ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: [17, 21]
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Install OpenMP on Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt install libomp-dev -y
      - uses: actions/checkout@v4
      - uses: NcStudios/VulkanCI@v1.0
        with:
          sdkVersion: 1.3.283.0
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test
      - name: Store test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-jdk-${{ matrix.jdk }}
          path: ./**/build/reports
