name: Testing with Java 17 and Java 21 on Linux

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test_ubuntu:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        jdk: [17, 21]
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y vulkan-validationlayers mesa-vulkan-drivers libomp-dev
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test --no-daemon
      - name: Store test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports
