name: Testing BC7 encoding on Windows, MacOS, and in a Docker container

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test --tests "com.github.knokko.compressor.TestBc7Compression.testCompressDreamShrine"
      - name: Store test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: windows-test-results
          path: build/reports
  test_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test --tests "com.github.knokko.compressor.TestBc7Compression.testCompressDreamShrine"
      - name: Store test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: macos-test-results
          path: build/reports
  test-docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - uses: actions/checkout@v4
      - run: apt update
      - run: apt install openjdk-17-jdk libomp-dev -y
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test --tests "com.github.knokko.compressor.TestBc7Compression.testCompressDreamShrine"
      - name: Store test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docker-test-results
          path: build/reports
